name: Github actions for rust cross compile
run-name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release --target aarch64-unknown-uefi && mv target/x86_64-unknown-uefi/release/uefi-from-scratch.efi target/x86_64-unknown-uefi/release/bootx64.efi

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-uefi/release/bootx64.efi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}